# RIM Experiment Overview

Lists all recorded runs and their key parameters.

In [24]:
import pandas as pd
from rim_teleop.data import ExperimentRegistry

DATA_DIR = "/home/athena/csirois/data/franka/rim"

registry = ExperimentRegistry(DATA_DIR)
runs = registry.list_runs()
print(f"{len(runs)} runs found in {DATA_DIR}")

72 runs found in /home/athena/csirois/data/franka/rim

In [25]:
summary_df = pd.DataFrame([r.summary() for r in runs])
summary_df

,name,created_at,rim_enabled,force_feedback,stiffness,damping,contact_surface,haptic_hz,control_hz,tool_tip_offset
0,run_20260522_161725,2026-05-22 16:17:25,True,rim,1000.0,90.0,0.03,1000.0,50.0,"[0.0, 0.0, 0.043]"
1,run_20260522_160954,2026-05-22 16:09:54,True,rim,1000.0,90.0,0.03,1000.0,50.0,"[0.0, 0.0, 0.043]"
2,run_20260522_155110,2026-05-22 15:51:10,True,rim,1000.0,90.0,0.03,1000.0,50.0,"[0.0, 0.0, 0.043]"
3,run_20260522_154437,2026-05-22 15:44:37,True,rim,1000.0,90.0,0.03,1000.0,50.0,"[0.0, 0.0, 0.043]"
4,run_20260522_154225,2026-05-22 15:42:25,True,rim,1000.0,90.0,0.03,1000.0,50.0,"[0.0, 0.0, 0.043]"
...,...,...,...,...,...,...,...,...,...,...
67,run_20260424_122854,2026-04-24 12:28:54,None,NaN,1000.0,90.0,0.00,1000.0,50.0,None
68,run_20260424_122824,2026-04-24 12:28:24,None,NaN,1000.0,90.0,0.00,1000.0,50.0,None
69,run_20260424_122742,2026-04-24 12:27:42,None,NaN,1000.0,90.0,0.00,1000.0,50.0,None
70,run_20260424_122143,2026-04-24 12:21:43,None,NaN,1000.0,90.0,0.00,1000.0,50.0,None
71,run_20260424_121938,2026-04-24 12:19:38,None,NaN,1000.0,90.0,0.00,1000.0,50.0,None

## Filter runs

In [26]:
# Example: only RIM-enabled runs with force feedback
filtered = summary_df[summary_df["rim_enabled"] == True]
filtered

,name,created_at,rim_enabled,force_feedback,stiffness,damping,contact_surface,haptic_hz,control_hz,tool_tip_offset
0,run_20260522_161725,2026-05-22 16:17:25,True,rim,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
1,run_20260522_160954,2026-05-22 16:09:54,True,rim,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
2,run_20260522_155110,2026-05-22 15:51:10,True,rim,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
3,run_20260522_154437,2026-05-22 15:44:37,True,rim,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
4,run_20260522_154225,2026-05-22 15:42:25,True,rim,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
5,run_20260521_160401,2026-05-21 16:04:01,True,rim,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
8,run_20260521_155836,2026-05-21 15:58:37,True,robot,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
9,run_20260521_155251,2026-05-21 15:52:51,True,rim,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
10,run_20260521_154934,2026-05-21 15:49:34,True,none,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
11,run_20260521_144728,2026-05-21 14:47:28,True,none,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
12,run_20260521_144032,2026-05-21 14:40:32,True,none,1000.0,90.0,0.030,1000.0,50.0,"[0.0, 0.0, 0.043]"
13,run_20260521_143654,2026-05-21 14:36:54,True,none,1000.0,90.0,0.036,1000.0,50.0,"[0.0, 0.0, 0.043]"
14,run_20260521_143551,2026-05-21 14:35:51,True,none,1000.0,90.0,0.036,1000.0,50.0,"[0.0, 0.0, 0.043]"
15,run_20260521_120819,2026-05-21 12:08:19,True,none,1000.0,90.0,0.036,1000.0,50.0,"[0.0, 0.0, 0.043]"
16,run_20260521_113859,2026-05-21 11:38:59,True,none,1000.0,90.0,0.036,1000.0,50.0,"[0.0, 0.0, 0.043]"
17,run_20260521_113547,2026-05-21 11:35:47,True,rim,1000.0,90.0,0.036,1000.0,50.0,"[0.0, 0.0, 0.043]"
18,run_20260520_174058,2026-05-20 17:40:58,True,rim,1000.0,90.0,0.000,1000.0,50.0,None
19,run_20260520_173809,2026-05-20 17:38:09,True,rim,1000.0,90.0,0.000,1000.0,50.0,None
20,run_20260520_173632,2026-05-20 17:36:32,True,none,1000.0,90.0,0.000,1000.0,50.0,None
21,run_20260520_173326,2026-05-20 17:33:26,True,none,1000.0,90.0,0.000,1000.0,50.0,None
22,run_20260520_173137,2026-05-20 17:31:37,True,none,1000.0,90.0,0.000,1000.0,50.0,None
23,run_20260520_172843,2026-05-20 17:28:43,True,none,1000.0,90.0,0.000,1000.0,50.0,None
24,run_20260519_175240,2026-05-19 17:52:40,True,none,1000.0,90.0,0.000,1000.0,50.0,None
25,run_20260519_171904,2026-05-19 17:19:04,True,none,1000.0,90.0,0.000,1000.0,50.0,None
26,run_20260519_165442,2026-05-19 16:54:42,True,none,1000.0,90.0,0.000,1000.0,50.0,None
27,run_20260519_164935,2026-05-19 16:49:35,True,none,1000.0,90.0,0.000,1000.0,50.0,None
29,run_20260519_163730,2026-05-19 16:37:30,True,none,1000.0,90.0,0.000,1000.0,50.0,None

## Full config of a specific run

In [11]:
import json

run = registry.latest()  # or registry.get("run_20260521_160401")
print(json.dumps(run.config, indent=2))

{
  "rates": {
    "control_rate_hz": 50.0,
    "model_rate_hz": 50.0,
    "rim_rate_hz": 1000.0,
    "haptic_rate_hz": 1000.0
  },
  "interface": {
    "axis": "z",
    "stiffness": 1000.0,
    "damping": 90.0,
    "contact_surface": 0.03,
    "contact_stiffness": 10000.0,
    "contact_damping": 100.0,
    "force_scale": 0.1,
    "force_cap": 12.0,
    "rim_enabled": true,
    "force_feedback": "rim"
  },
  "safety": {
    "stale_state_timeout_s": 0.2,
    "stale_model_timeout_s": 0.25,
    "deadman_required": false
  },
  "inverse3": {
    "uri": "ws://localhost:10001",
    "scale": 1.0,
    "i3_origin": [
      0.0,
      -0.17,
      0.16
    ],
    "i3_origin_rpy": [
      0.0,
      0.0,
      90.0
    ],
    "i3_origin_rpy_degrees": true,
    "center_on_start": true,
    "enable_force_feedback": true,
    "stiffness": 150.0,
    "force_cap": 12.0,
    "orientation_default": [
      0.0,
      1.0,
      0.0,
      0.0
    ],
    "interface_axis": "z",
    "interface_workspace_scale": 1.0,
    "interface_force_scale": 0.1
  },
  "robot": {
    "namespace": "fr3",
    "controller_name": "osc_pd_controller",
    "trajectory_length": 5,
    "trajectory_dt": 0.1,
    "wrench_filter_alpha": 0.1
  },
  "model": {
    "urdf_package": "franka_rim",
    "urdf_relative_path": "models/fr3_franka_hand.urdf",
    "ee_frame_name": "fr3_hand_tcp",
    "filter_alpha_q": 0.3,
    "filter_alpha_q_dot": 0.2,
    "filter_alpha_tau": 0.2,
    "tool_tip_offset": [
      0.0,
      0.0,
      0.043
    ]
  },
  "logging": {
    "enabled": true,
    "sinks": [
      "file_sink",
      "foxglove_sink"
    ],
    "file_sink": {
      "enabled": true,
      "output_dir": "/home/athena/csirois/data/franka/rim",
      "run_name": null,
      "flush_hz": 20.0
    },
    "foxglove_sink": {
      "enabled": true,
      "host": "0.0.0.0",
      "port": 8765,
      "topic_prefix": "/rim"
    }
  },
  "dry_run": false
}